# name: Notify Slack on Release

# on:
#   release:
#     types:
#       - created
#       - push

# jobs:
#   notify_slack:
#     runs-on: ubuntu-latest
#     name: Notify Slack on Release
#     steps:
#       - name: Notify Slack on Release
#         uses: instantish/notify-slack-on-release@1.0.0
#         with:
#           slack_webhook_url: ${{ secrets.SLACK }}

# name: slack_github_action
# on: 
#   release:
#     types:
#       - created
#       - push
#       - pull_request
# jobs:
#   slack_notifier:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send notification on Slack using Webhooks
#         uses: slackapi/slack-github-action@v1.24.0
#         with:
#           payload: |
#             {
#             "text": "Git push done in the repo , and PR is created"
#             }
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}

name: Slack Notifications for Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "text": "PR is created"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
          channel: 'github'
          username: 'GitHub Actions'
          icon_emoji: ':rocket:'
          text: 'New pull request created: ${{ github.event.pull_request.html_url }}'

